### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by rhajizadeh** [adamgibbons/ics#101]
Hi
Thank you for your module
Please add typescript support.

**Comment by adamgibbons** [comment]
I don't have the bandwidth but would love Typescript support as well.

**Comment by mmiszy** [comment]
@adamgibbons would you consider accepting a PR for this?
Would you like to rewrite the source of this library in TypeScript or just add typing as `index.d.ts`?

**Comment by adamgibbons** [comment]
Both, really :-)

Adding typing in `index.d.ts` is definitely a win, and a much quicker win. Were we to rewrite this in TS, I think I'd want to improve the api overall, make some breaking changes, and release a 3x. E.g. two things I didn't anticipate in the beginning were that I'd eventually want to  1) parse ICS files, or 2) support more of (RFC 5545)[https://tools.ietf.org/html/rfc5545].

**Comment by mmiszy** [comment]
Me, or my team, can take care of writing `index.d.ts` file. We've already started, so why not share it with everyone :)

**Comment by mmiszy** [comment]
https://github.com/adamgibbons/ics/pull/118
