### ISSUE TITLE
Time zone support messes up in version 2.13

### ISSUE THREAD

**Issue by TokkeDev** [adamgibbons/ics#108]
When upgrading from version 2.12.1 to 2.13.0, all my events that are created in local time now jumps ahead two hours when are viewed in Apple Calendar og on Google Calendar. I'm currently in the GMT+2 time zone, so an event that was supposed to begin 9.15 now starts at 11.15.

**Comment by futin** [comment]
I can confirm the same behaviour. For now, I'll switch on lower version, but this should be fixed.

**Comment by jcaron23** [comment]
There is indeed now a mismatch between the documentation (which states that dates in the createEvent call are local) and what happens (which considers them UTC). This is probably related to #98 which fixed UTC management, coupled with the fact that the default type in setDate is utc, not local. Will check further.

**Comment by jcaron23** [comment]
Submitted PR #113 which should fix this.

**Comment by adamgibbons** [comment]
Addressed by #115
