### ISSUE TITLE
X- field support

### ISSUE THREAD

**Issue by strarsis** [adamgibbons/ics#119]
Are custom/proprietary X- fields supported like `X-ALT-DESC` used by Outlook?

**Comment by adamgibbons** [comment]
They are not supported but they should be.

**Comment by brennongs** [comment]
I just added support for `X-MICROSOFT-CDO-BUSYSTATUS`(see #120) , I'd be happy to help with others. @adamgibbons do you want to eventually support all of them? Maybe we should compile a list of priorities so we can go about adding them in an organized manner?

**Comment by strarsis** [comment]
@brennongs: Thanks! Though it is a very specific `X-` field.
Ideally all kinds of X-fields should be supported, without hardcoding the allowed ones into the library.
`X-ALT-DESC` is a very important one as it allows to add HTML to an item (e.g. calendar/appointment item): `X-ALT-DESC;FMTTYPE=text/html:`

**Comment by adamgibbons** [comment]
I used to use the `x-attr-foo="bar"` approach in front-end web development before React et al. came along, so I get the power of expanding the api to support `X-whatever`. However, in the interest of trying to enforce a slightly stricter model, I'm inclined to implement `X-ALT-DESC` and whatever other common ones are out there as the need arises. PRs like @brennongs are clean and easy to ship straight to NPM. If I get feedback that I'm bottlenecking people from building stuff, then I am definitely happy to reconsider.

**Comment by bbbryan14** [comment]
is someone actively working on a PR for `X-ALT-DESC` or should I take a stab at it?

**Comment by adamgibbons** [comment]
@bbbryan14 go for it 👍

**Comment by machinecode** [comment]
Hi Adam,

Is this feature added? I couldn't see the relevant pull request.

**Comment by adamgibbons** [comment]
@machinecode no sir, I just closed due to inactivity - there was no PR

**Comment by machinecode** [comment]
ok, Let me try it then :)

**Comment by Gr8z** [comment]
+1
