### ISSUE TITLE
VALARM is missing DESCRIPTION

### ISSUE THREAD

**Issue by YM-KA** [adamgibbons/ics#122]
Hi! I have created a event with an alarm. 
The problem is that the output is missing DESCRIPTION in the VALARM section, which seems to be mandatory. I have validated the ics file here [https://icalendar.org/validator.html](https://icalendar.org/validator.html) and got error
<code>Missing DESCRIPTION property in VALARM near line # 17</code>

Outlook is also complaining when subscribing to the file. 

Am I only missing to supply a value somewhere? 
My code and output below. 

 ```
let myEvents = []
myEvents.push({
  uid: '-LovTg9y9HPDCHu8mVnD',
  start [2019, 9, 17, 8, 0],
  duration: { hours: 0, minutes: 30 },
  title: 'Purjolök',
  description: 'En grönsak i lökfamiljen',
  url: `https://app.mysite.se/r/edit/${uid}`, 
  categories: ['Mat'],
  status: 'CONFIRMED', 
  busyStatus: 'BUSY', 
  alarms: [{
    action: 'display', 
    trigger: { hours: 0, minutes: 10, before: true }
  }]
})

ics.createEvents(myEvents, (error, value) => {
  res.set('Content-Type', 'text/calendar;charset=utf-8')
  res.attachment('calendar.ics')
  res.status(200).send(value)
}
```
The output looks like this
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:adamgibbons/ics
METHOD:PUBLISH
X-PUBLISHED-TTL:PT1H
BEGIN:VEVENT
UID:-LovTg9y9HPDCHu8mVnD
SUMMARY:Purjolök
DTSTAMP:20191021T094900Z
DTSTART:20190917T080000Z
DESCRIPTION:En grönsak i lökfamiljen
URL:https://app.mysite.se/r/edit/-LovTg9y9HPDCHu8mVnD
STATUS:CONFIRMED
CATEGORIES:Matlista
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT
END:VALARM
DURATION:PT30M
END:VEVENT
END:VCALENDAR
```

Kind regards
Kazuyuki

**Comment by giuliano-barberi-tf** [comment]
You can specify the `description` in your alarm object and it does work. The documentation just needs to be updated.

**Comment by YM-KA** [comment]
😄 Did not even try that. Yes it works - many thanks! 🤓
