### ISSUE TITLE
Possible to set X-WR-CALNAME

### ISSUE THREAD

**Issue by YM-KA** [adamgibbons/ics#123]
Is it possible to set <code>X-WR-CALNAME</code>?
I cannot find anything about this value in the documentation. 

Would be great to be able to set - otherwise the default value when subscribing to .ics is set to "Undefined". 

Many thanks Kazuyuki

**Comment by dcdarrow83** [comment]
Thank you. I can't get it yet..

**Comment by YoomiAB** [comment]
A (quite messy) workaround is to simply split the output and insert the tag manually - see below. 

```
    // Error handling - if user doesn't exist
    value = value === null ? `BEGIN:VCALENDAR\nEND:VCALENDAR` : value
    res.set('Content-Type', 'text/calendar;charset=utf-8')
    res.attachment('calendar.ics')
    // Insert X-WR-CALNAME
    const parts = value.split('BEGIN:VCALENDAR')
    const result = `BEGIN:VCALENDAR\nX-WR-CALNAME:myWrCalName${parts[1]}`
```
This is far from fool-proof though. 🤔

**Comment by YM-KA** [comment]
A (quite messy) workaround is to simply split the output and insert the tag manually - see below.

```
    // Error handling - if user doesn't exist
    value = value === null ? `BEGIN:VCALENDAR\nEND:VCALENDAR` : value
    res.set('Content-Type', 'text/calendar;charset=utf-8')
    res.attachment('calendar.ics')
    // Insert X-WR-CALNAME
    const parts = value.split('BEGIN:VCALENDAR')
    const result = `BEGIN:VCALENDAR\nX-WR-CALNAME:myWrCalName${parts[1]}`
```

This is far from fool-proof though. 🤔
