### ISSUE TITLE
ICS in Exchange/Outlook updates not working

### ISSUE THREAD

**Issue by dominicjordan** [adamgibbons/ics#128]
I have generated an ICS file with an appointment (example 1). This appointment can change often so I would like to send out new ICS files (using my backend). This would normally work by sending the file with the same appointment UID and a higher SEQUENCE (example 2). This works great with iCloud Calendar where the existing item gets moved to the new date but does NOT work with Exchange/Google Calendar. 

**Any ideas in how to make ICS updates update the existing calendar item in Exchange (without complicated subscriptions/setting up a webcal server)?**

Example 1: Initial ICS

    BEGIN:VCALENDAR
    VERSION:2.0
    CALSCALE:GREGORIAN
    PRODID:adamgibbons/ics
    METHOD:PUBLISH
    X-PUBLISHED-TTL:PT1H
    BEGIN:VEVENT
    UID:2211@planning.company.nl
    SUMMARY:Planning Item 01
    DTSTAMP:20191123T170300Z
    DTSTART:20191123T123000Z
    DTEND:20191123T143000Z
    SEQUENCE:1
    DESCRIPTION:Planning Item 01
    END:VEVENT
    END:VCALENDAR

Example 2: Updated ICS

    BEGIN:VCALENDAR
    VERSION:2.0
    CALSCALE:GREGORIAN
    PRODID:adamgibbons/ics
    METHOD:PUBLISH
    X-PUBLISHED-TTL:PT1H
    BEGIN:VEVENT
    UID:2211@planning.company.nl
    SUMMARY:Planning Item 01
    DTSTAMP:20191129T170300Z
    DTSTART:20191129T123000Z
    DTEND:20191129T143000Z
    SEQUENCE:0
    DESCRIPTION:Planning Item 01
    END:VEVENT
    END:VCALENDAR

**Comment by adamgibbons** [comment]
The latest version of this package now supports the `CREATED` and `LAST-MODIFIED` attributes - try setting the former on the first event, and add the latter on the updated event. If that doesn't resolve your issue please open another PR.
