### ISSUE TITLE
how to sync with outlook and google calendar

### ISSUE THREAD

**Issue by chiraggmodi** [adamgibbons/ics#130]
Hi sorry to put this here, 
but I have not found any solution for this issue and hoping that I get help here

So I am using this module to genrate ICS file for calendar, now I want to get sync when every file is get updated in google calendar or in outlook, same as basecamp.

so when new event added by user I also want to update that event in file and get sync with google and outlook 

So anyone have any idea how this can be achieve?

**Comment by adamgibbons** [comment]
The latest version of this package now supports the `CREATED` and `LAST-MODIFIED` attributes - try setting the former on the first event, and add the latter on the updated event. If that doesn't resolve your issue please open another PR.
