### ISSUE TITLE
cannot find module './dist'

### ISSUE THREAD

**Issue by mmuurr** [adamgibbons/ics#131]
Hi, I'm having trouble using `ics` after a clean node (v13.5.0) installation.
Here are my (I think, reproducible) steps:
```
> npm install github:adamgibbons/ics
```
... and this succeeds.
Then, once in the node REPL, this:
```
> require('ics')
Uncaught Error: Cannot find module './dist'
Require stack:
- /PATH/TO/MY/PROJECT/node_modules/ics/index.js
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/PATH/TO/MY/PROJECT/node_modules/ics/index.js',
    '<repl>'
  ]
}
```
(where `/PATH/TO/MY/PROJECT` is replaced by the actual path :-)

Any ideas?

**Comment by mmuurr** [comment]
Nevermind ... I was trying to install from the github source, but that doesn't seem to be working for me (user error, I'm sure).
When I install from npm's disto, it works.

**Comment by adamgibbons** [comment]
`npm run build` should generate the `dist` directory you were looking for.
