### ISSUE TITLE
Prototype Pollution vulnerability on @hapi/joi > @hapi/hoek

### ISSUE THREAD

**Issue by heiso** [adamgibbons/ics#134]
npm audit source : https://www.npmjs.com/advisories/1468

Fix : bump all @hapi/hoak occurences to ^8.5.1 in package-lock.json https://github.com/adamgibbons/ics/blob/master/package-lock.json#L839

Thanks !

Have a 🍪

**Comment by adamgibbons** [comment]
Fixed by #139
