### ISSUE TITLE
`@hapi/joi` dependency - necessary?

### ISSUE THREAD

**Issue by rh389** [adamgibbons/ics#149]
Just evaluating this lib for use in a project and the one issue that stood out for me was the dependency on `@hapi/joi`, which has a chain of various dependencies.

This is only used in `src` for `validateEvent`. This isn't exported or part of the package's public API, but it's used as part of `createEvent`. Is it really necessary to validate the package's output at runtime? Seems like more of a job for unit tests.

If it's possible to move `@hapi/joi` into `devDependencies` and drop this runtime check that'd be a nice win (and presumably also a good performance boost for `createEvent`, if that matters)

**Comment by adamgibbons** [comment]
Great suggestion, I'll take a look

**Comment by ggascoigne** [comment]
I'd love this, @hapi/joi is also rather large so being able to drop it for that reason as well would be a solid plus.

**Comment by atomicpages** [comment]
@adamgibbons any progress on this? I'd be happy to help out with this by sending a PR. LMK 👍 .  One the same lines moving away from `uuid` and toward `nanoid` will further reduce bundle size

**Comment by rh389** [comment]
Just to note that when I raised this I was mistaken about the use of this dependency - it's actually used to validate event _input_, so there'd be some loss of safety by removing it (albeit fairly minimal - especially for typescript users where the runtime checks mostly duplicate the type annotations).

IMO it's not worth the extra package weight to validate consumer input (and there are lighter solutions than `@hapi/joi`), but it is a judgement call.

**Comment by adamgibbons** [comment]
@atomicpages No progress on this. I agree that hapi is too large and there are better alternatives - however validation of some sort is necessary and that's why I haven't simply dropped hapi. I'm open to any suggestions and I'm always interested in removing dependencies/reducing dependency size.

**Comment by 0xdevalias** [comment]
Looks like there is a PR opened 25 days ago that will replace this with `yup`, keeping the runtime checks, but reducing the size.

**Comment by 0xdevalias** [comment]
> One the same lines moving away from `uuid` and toward `nanoid` will further reduce bundle size

Please! I was just about to say the same, then saw this comment.

- https://github.com/ai/nanoid/

**Comment by adamgibbons** [comment]
Heard and merged!

**Comment by 0xdevalias** [comment]
Thanks for getting that PR merged @adamgibbons 

Curious what your thoughts are on using nanoid as well, as mentioned above?
