### ISSUE TITLE
Feature request: Allow the developer to disable adding DTSTAMP property to events

### ISSUE THREAD

**Issue by mikoprus** [adamgibbons/ics#157]
Current situation: 
createEvents function creates DTSTAMP for every event and doesn't provide a way to disable this

Why is this a problem: 
Would be nice to not have it there and use for example a file hash for versioning, useful in cases where software pulls new file and wants to know if it changed based on file hash

Desired situation:
 option to disable adding DTSTAMP on createEvents function

**Comment by adamgibbons** [comment]
Are you saying that the DTSTAMP value is the same for every event when using `createEvents`?

**Comment by mikoprus** [comment]
I want to be able to create events that don't have a `DTSTAMP`

**Comment by adamgibbons** [comment]
`DTSTAMP` is a required event prop in the RFC, so this lib needs to include it. https://tools.ietf.org/html/rfc5545#section-3.6.1

**Comment by mikoprus** [comment]
`DTSTAMP` is not required when specyfing `METHOD` property, would you consider adding `METHOD` property then? If so I'm happy to contribute. :)

**Comment by adamgibbons** [comment]
Absolutely, happy to consider

**Comment by mikoprus** [comment]
I was mistaken about `DTSTAMP` not being required when specyfing `METHOD`
