### ISSUE TITLE
Creating multiple events fails with 'start' must be an array

### ISSUE THREAD

**Issue by IvieH** [adamgibbons/ics#163]
I am not sure if I am doing something wrong, or there may be an error in the code.

I am trying to add multiple events like in the examples, but it fails with an error that start must be an array.

It looks like the buildEvents call is not accounting for an array of events.
`
function buildEvent() {
  var attributes = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
  var title = attributes.title,
      productId = attributes.productId,
      method = attributes.method,
      uid = attributes.uid,
      sequence = attributes.sequence,
      start = attributes.start,
      startType = attributes.startType,
      duration = attributes.duration,
      end = attributes.end,
      description = attributes.description,
      url = attributes.url,
      geo = attributes.geo,
      location = attributes.location,
      status = attributes.status,
      categories = attributes.categories,
      organizer = attributes.organizer,
      attendees = attributes.attendees,
      alarms = attributes.alarms,
      recurrenceRule = attributes.recurrenceRule,
      created = attributes.created,
      lastModified = attributes.lastModified,
      calName = attributes.calName; // fill in default values where necessary

  var output = Object.assign({}, _defaults["default"], attributes); // remove falsey values

  var cleanOutput = (0, _pickBy["default"])(output, _identity["default"]);
  return cleanOutput;
}`
I am not sure where to go from here.

Great job on this though

**Comment by IvieH** [comment]
My fault

**Comment by avlima** [comment]
Please, tell me what the solution was, I have the same problem!
