### ISSUE TITLE
busyStatus missing from typescript types

### ISSUE THREAD

**Issue by taxilian** [adamgibbons/ics#164]
I'm new to this library, so I'm not certain which is incorrect, but either the docs are incorrect saying that `busyStatus` is a valid option or `index.d.ts` is incorrect because it's missing busyStatus.

Just FYI =]

**Comment by adamgibbons** [comment]
@taxilian thanks for pointing this out - `index.d.ts` is behind - happy to merge a PR if you want to submit one.
