### ISSUE TITLE
Multiple events "start" must be an array

### ISSUE THREAD

**Issue by avlima** [adamgibbons/ics#167]
I'm having trouble recording multiple events, I followed the steps in the documentation but this error insists on appearing.

These are the events I'm trying to record:

`{
            title: 'test 1',
            description: 'Nightly thing I do',
            busyStatus: 'FREE',
            start: ['2021', '2', '11', '13', '0'],
            duration: {minutes: 50},
          },
          {
            title: 'test 2',
            description: 'Nightly thing I do',
            busyStatus: 'FREE',
            start: ['2021', '2', '11', '16', '0'],
            duration: {minutes: 50},
          }`

**Comment by cavazzatommaso** [comment]
Sorry i have the same issue. How did you managed to resolve this?
