### ISSUE TITLE
URL not working to window calendar

### ISSUE THREAD

**Issue by avlima** [adamgibbons/ics#169]
The same event added for other calendars displays the URL, but in the window calendar, it does not.
Any solution?

<img width="1362" alt="Screen Shot 2021-02-12 at 14 17 54" src="https://user-images.githubusercontent.com/13434925/107800200-3edc7500-6d3d-11eb-9b23-7a9516629a1b.png">

The link is not recognized by Windows Calendar apps, if not possible to correct, please add link to the event description also

**Comment by adamgibbons** [comment]
@avlima would you provide a stripped down `.ics` file where this works as you expect, and one generated by this library that doesn't work, so that I can see them side-by-side?

**Comment by avlima** [comment]
> @avlima would you provide a stripped down `.ics` file where this works as you expect, and one generated by this library that doesn't work, so that I can see them side-by-side?

I solved, I mistake :/
