### ISSUE TITLE
Unable to use this lib in the front

### ISSUE THREAD

**Issue by rdubigny** [adamgibbons/ics#17]
This lib can't be used in a browser since there is a dependance with `fs` https://github.com/adamgibbons/ics/blob/master/lib/ics.js#L2 .

@adamgibbons can you make this requirement optionnal ?

**Comment by adamgibbons** [comment]
@rdubigny I agree this would make it more useful. Will put it on the to-do shortlist :-)

**Comment by darylteo** [comment]
This library can be used without 'fs' by avoiding `createEvent` method (as that writes to a file). Use `buildEvent` instead to get a string representation.

In webpack, we also have to shim fs with https://webpack.github.io/docs/configuration.html#node

```
node: {
  fs: null,
}
```

Hope that helps.
