### ISSUE TITLE
Is it possible to set EXDATE with this library?

### ISSUE THREAD

**Issue by Ovsyanka83** [adamgibbons/ics#172]

**Comment by lights0123** [comment]
Until a way to add custom properties is exposed, you can use a hacky workaround by using any property that isn't sanitized with `foldLine` in [src/pipeline/format.js](https://github.com/adamgibbons/ics/blob/31d4496ace2b9aa3c2b4022349cf827c559db50b/src/pipeline/format.js) (`uid`, `timestamp`, `sequence`, or `recurrenceRule`), and then passing `'\r\n'` and then `EXDATE:<your data>`. For example:

```js
recurrenceRule: 'FREQ=DAILY\r\nEXDATE:<data>',
```

**Comment by lights0123** [comment]
I would leave this open, as there *should* be a way to do this without this hacky workaround.
