### ISSUE TITLE
index.ts missing busyStatus property

### ISSUE THREAD

**Issue by lulucious** [adamgibbons/ics#175]
Hi, 
It seems that type ics.EventAttributes definition misses busyStatus property in index.d.ts
Can you please check if the error is in index.d.ts or if busyStatus is actually deprecated ? 
Thanks for your help!

**Comment by spideep** [comment]
I have detected the same issue as well.
This causes:
`error TS2345: Argument of type ... is not assignable to parameter of type 'EventAttributes'`
