### ISSUE TITLE
htmlDescription on event not importing, only description

### ISSUE THREAD

**Issue by wadewadewadewadewadewade** [adamgibbons/ics#179]
Has anyone had issues getting the HTML to appear in calendar apps like Google Calendar or Apple Calendar?

If I have `<b>some html</b>` as the htmlDescription for an event and `some html` as the description, only `some html ` appears in the calendar date in the app I'm importing the ics into.

Thanks!

**Comment by adamgibbons** [comment]
I don't think there's great support in calendar apps for supporting HTML in descriptions, but hopefully #200 gets you closer to your objective.
