### ISSUE TITLE
Replace uuid with nanoid to reduce the bundle size

### ISSUE THREAD

**Issue by 0xdevalias** [adamgibbons/ics#182]
> One the same lines moving away from `uuid` and toward `nanoid` will further reduce bundle size
> 
> _Originally posted by @atomicpages in https://github.com/adamgibbons/ics/issues/149#issuecomment-760349672_

---

> > One the same lines moving away from `uuid` and toward `nanoid` will further reduce bundle size
> 
> Please! I was just about to say the same, then saw this comment.
> 
> * https://github.com/ai/nanoid/
> 
> _Originally posted by @0xdevalias in https://github.com/adamgibbons/ics/issues/149#issuecomment-844940209_

---

For some visual stats, according to `bundlephobia`, `1.5%` (`~2.46kB`) of this lib's `160.8kB` (min) size comes from `uuid`:

(see https://github.com/adamgibbons/ics/issues/149#issuecomment-844932986 + https://github.com/adamgibbons/ics/pull/178 for the issue + PR to fix the size issues related to `joi`)

- https://bundlephobia.com/result?p=ics@2.27.0

![image](https://user-images.githubusercontent.com/753891/118960756-f4573e00-b9a6-11eb-8afc-92c20ffa5e96.png)

**Comment by Flowr-es** [comment]
nanoid is merged, can this be closed than?
