### ISSUE TITLE
crypto.randomBytes is not a function

### ISSUE THREAD

**Issue by berenteb** [adamgibbons/ics#193]
I am trying to use the createEvent function, and a TypeError showed up in the console breaking everything. If I comment out this part of the implementation, it goes away. I am using TypeScript.

**Comment by buschco** [comment]
If you are using `react-native` or similar environments that do no support the `crypto` API out of the box, try to install [`react-native-get-random-values polyfill`](https://github.com/uuidjs/uuid) and import it somewhere before this package `import 'react-native-get-random-values';`

For more info see [here](https://github.com/uuidjs/uuid#react-native--expo)

**Comment by adamgibbons** [comment]
Should be resolved by switching from uuid to nano.
