### ISSUE TITLE
ICS Update Not Working in Google Calendar

### ISSUE THREAD

**Issue by KeshavGoswami** [adamgibbons/ics#199]
Hello,
I am currently sending an event through a mail with an attached .ics file. After accepting the event (which works nicely) I want to try to update the event by sending another mail with another attached .ics file, but accepting the new file just adds a new  event and does not remove the old, outdated event. Of course I have double checked to see so that the uid are the same and that the sequence is incremented.

When I send these mails to my personal Outlook account it works like expected. I am sending the mail with another Outlook account which is set to be the organizer of the event.

If anyone could tell me what I am doing wrong I would be glad to hear it.

**Comment by Nits7029** [comment]
@adamgibbons I am also stuck on this same issue, would be great if you guide me. Thanks

**Comment by Algoritm211** [comment]
Hello, this is not working only because at the end of generated file library generates one unnecessary empty line using `\n`. If you will remove it - it will work

**Comment by AdrianCurtin** [comment]
Some comments here that might be relevant but I haven't been able to get it to work myself.

https://stackoverflow.com/questions/14712929/icalendar-ics-update-not-working-in-google-calendar/49585109#49585109

The current ics version does not support CUTYPE or X-NUM-GUESTS and it's possible that these fields are required
