### ISSUE TITLE
Why are ISO start times converted to iCal local time?

### ISSUE THREAD

**Issue by cava23** [adamgibbons/ics#20]
When I provide this library a start time in ISO format, the resulting iCal string has the start time as local time (Form #1 in the RFC, https://icalendar.org/iCalendar-RFC-5545/3-3-5-date-time.html). I would expect an absolute time to remain absolute in the resulting iCal string (Form #2). Specifically, what is the purpose of line 83 in lib/ics.js? How can I specify that the iCal string use form #2 when providing the start time in an absolute format?

**Comment by emilianop11** [comment]
I have exactly the same problem, Im providing the starting and ending time in Form 2, but the output is automatically moved to form 1. I think it should be kept in form 1 with no changes.

**Comment by cava23** [comment]
@emilianop11 I added support for DSTART here: https://github.com/Tredsite/ics

**Comment by tamoyal** [comment]
There def seems to be some weird default behavior for end time! @cava23 Thanks for the fix. The issue can be replicated by ...
```
var icsProps = {};
icsProps.start = someStartTime.toISOString(); // This start time is in UTC
let defaultHourOffset = 1;
let endTime = new Date(someStartTime.getTime());
endTime.setTime(endTime.getTime() + (defaultHourOffset*60*60*1000)); // add 1 hour
icsProps.end = endTime.toISOString(); 
console.log(icsProps.end); // looks good - 1 hour added to start time
let ics = new ICS();
console.log(ics.buildEvent(icsProps)); // looks bad - end time converted to local time (or just hard coded to EST) with no respect for UTC timezone 
```

**Comment by adamgibbons** [comment]
Closing because this issue should be resolved by upgrading to v2.
