### ISSUE TITLE
Handle organizer names with special characters correctly

### ISSUE THREAD

**Issue by jfarre90** [adamgibbons/ics#249]
### Issue
In some scenarios, the organizer name might have commas in it. With the current logic, the generation would still seem to work properly, but the .ics data would fail to be synced correctly to any calendar application, as there is an error with the formatting of the ORGANIZER field.

### Proposals
Any of this would prevent against this issue:
1. Always wrap the organizer name in double quotes, which would allow the commas in it. i.e. in the logic here, update to `formattedOrganizer += `"${name}"` || 'Organizer'`https://github.com/adamgibbons/ics/blob/master/src/utils/set-organizer.js#L1. (This could potential break implementations of this library)
2. Escape potentially breaking characters using the existing `formatText` function (Might be the less impactful solution): https://github.com/adamgibbons/ics/blob/master/src/utils/format-text.js#L1. So the logic above would look something like: `formattedOrganizer += formatText(name) || 'Organizer'

**Comment by adamgibbons** [comment]
Fixed by #261
