### ISSUE TITLE
is this supported in safari?? 

### ISSUE THREAD

**Issue by Mikeks81** [adamgibbons/ics#27]
I'm having problems getting safari to name the file and not save as "unknown". it does go to the downloads however when opened it's in text/edit.  On download i do get an error of 'Failed to load resource: Frame load interrupted'  in the browser console.

**Comment by adamgibbons** [comment]
@Mikeks81 you're the first to point this out. Haven't checked it myself but I'll look into it when I get a chance.

**Comment by adamgibbons** [comment]
maybe related? http://stackoverflow.com/questions/15439922/datauri-for-ical-does-not-work-on-android-or-iphone

**Comment by Raghavendra92** [comment]
Is this still open? Even I have the same issue..does not work on safari

**Comment by Mikeks81** [comment]
If the problem is that you're using safari 10.1 or below the problem might be that it doesn't like the download attr. 
[http://caniuse.com/#feat=download ](http://caniuse.com/#feat=download )

**Comment by Raghavendra92** [comment]
hmm..I am facing this issue on safari-desktop..as per the link it says 10.1 should support download attr

**Comment by Mikeks81** [comment]
Sorry, i meant below 10.1. Is the 'untitled' ics file downloading with valid content and the name is untitled or is it not a valid ICS file?

**Comment by Raghavendra92** [comment]
It works on 10.1 . I was trying to open the data uri with window.open..when
I use href it works fine..thanks for the help
