### ISSUE TITLE
Npm package not up to date with git repository

### ISSUE THREAD

**Issue by rubenobbink** [adamgibbons/ics#279]
It seems that the code in https://www.npmjs.com/package/ics/v/3.8.0?activeTab=code is not up to date with the code in this repository. Is this intentional? I found out after running into the error with _runes.runes using the latest version from npm, and saw that the problem was fixed in the repository 3 months ago.

**Comment by adamgibbons** [comment]
Thanks for flagging - please let me know if this is resolved by `v3.8.1`.
