### ISSUE TITLE
Could you add support for UTC end time too?

### ISSUE THREAD

**Issue by loborobo** [adamgibbons/ics#28]

**Comment by mhewett** [comment]
Totally agree.  Start time and End time processing should be exactly the same in the simplest case.  End time doesn't handle UTC correctly.

**Comment by dylanjha** [comment]
@adamgibbons care to chime in here?

Is there a reason UTC end time isn't supported, this seems to be breaking some versions of Outlook Calendar.

**Comment by adamgibbons** [comment]
Looks like this is a bug - I'm happy to take a PR if anyone wants to fix it. I'm trying to release #32 ASAP which should resolve this.

**Comment by dylanjha** [comment]
@adamgibbons thanks for confirming the bug! @mcassagnes or I might be able to take a stab at patching this, would it be better to branch off v2 and work off that or better to branch off master and patch?

**Comment by adamgibbons** [comment]
@dylanjha up to you. v2 is where the energy is going so I'd say work off that - however if you need the patch in production right now, I'll merge your fix into master and publish it to npm.

**Comment by adamgibbons** [comment]
Closing because v2 has been released.
