### ISSUE TITLE
Support for recurring events?

### ISSUE THREAD

**Issue by nathanieltagg** [adamgibbons/ics#30]
This looks nice, but I'd like to use it to generate events for classes. Any support for recurring events likely?

**Comment by adamgibbons** [comment]
I haven't had a chance to work on this in a while, but definitely agree this would be a nice feature. Happy to accept a PR if you end up writing anything!

**Comment by a-type** [comment]
Looks like a PR was opened for this (https://github.com/adamgibbons/ics/pull/82), any possibility of merging and releasing?

**Comment by adamgibbons** [comment]
@a-type yes - reviewing #82 now.
