### ISSUE TITLE
support for multiple VEVENT in VCALENDAR

### ISSUE THREAD

**Issue by crebelsky** [adamgibbons/ics#33]
I'm planning to create some kind of event calendar, with several events coming from a api. Is it planned to implement some option to create multiple VEVENT's?

@adamgibbons thanks for the work so far!

**Comment by adamgibbons** [comment]
@crebelsky I can put this on the roadmap. In the meantime, you can probably create an array of event objects doing something like `[{ event1 }, { event2 }, ...].map(ics.buildEvent)`.

**Comment by crebelsky** [comment]
@adamgibbons thanks for putting this on the map. I already did it with a array and some more changes. Works as expected for now! Looking forward to v2!

**Comment by hibangun** [comment]
@crebelsky @adamgibbons do you have code example for this?

**Comment by adamgibbons** [comment]
@hibangun here you go - https://github.com/adamgibbons/ics/wiki/Creating-multiple-events

Hope this helps - let me know if you have questions. I'll build `createEvents` into the library soon but hopefully this will do exactly what you need in the meanwhile.

**Comment by seclace** [comment]
@adamgibbons Hi, you are creating interesting thing! But how I can write multiple events to the one `.ics` file with this library?

**Comment by svnindia** [comment]
@adamgibbons on every events its creating begin calendar wrapper, that's not the correct syntax

**Comment by svnindia** [comment]
Available in this PR https://github.com/adamgibbons/ics/pull/42
