### ISSUE TITLE
Compatibility with Outlook and iOS

### ISSUE THREAD

**Issue by panzupa** [adamgibbons/ics#39]
Hi,

I've started using this lib and it works great for Gmail. Email with ics attachment is recognized as meeting invite by Gmail, and special template for displaying meeting information is applied by Gmail.

Unfortunately, this does not happen when the same email with sam ics file is sent to somone@icloud.com / iOS device. It's displayed as an ordinary email with an attachment.  Polish popular email service poczta.wp.pl has the same problem.

What about MS Outlook? Will it recognize it or have same problem as Apple?

**Comment by adamgibbons** [comment]
@panzupa I have admittedly not tried this on MS Outlook or iOS, though I do know it works on current and previous versions of the OS X Calendar application. If you would like to troubleshoot any of this and submit a PR I'm happy to merge or help out.

**Comment by tetreault** [comment]
@panzupa did you ever resolve this? I'm working on a new project and considering this library but I need it to work across mail clients. Outlook supports `.ics` files, but have read in another sendgrid nodejs thread that you need to send a particular header along with the `.ics` file

**Comment by panzupa** [comment]
@tetreault No, I have not resolved that problem. However, I recall that you need to send ics as a special mime type which was not supported by mailgun JS API - a blocker for me.

Please look at this https://stackoverflow.com/questions/47111467/mailgun-send-calendar-meeting-event-request
