### ISSUE TITLE
best practice for saving ICS files

### ISSUE THREAD

**Issue by rubenabergel** [adamgibbons/ics#6]
It is said that files are saved in the "operating system's temporary directory". Was curious to know if you would recommend people to store these files elsewhere and how?
Thanks

**Comment by adamgibbons** [comment]
Saving to the temp directory was just a default behavior decision so that a user couldn't inadvertently create a bunch of events that never get cleaned up. You should save the file to whatever destination is easiest to access for you given your business requirements.
