### ISSUE TITLE
Sequence not a possible argument

### ISSUE THREAD

**Issue by AnthonyLamot** [adamgibbons/ics#64]
This is more of a question actually.

I noticed it's not possible to pass a "sequence" attribute. However it seems this is necessary if you want to update an event: https://tools.ietf.org/html/rfc5546#section-4.2.3

Any reason this has not been added? Is there another way to send updated events using this package?

**Comment by adamgibbons** [comment]
Interesting - I hadn't read that part of the spec. No reason it hasn't been added - if you're interested in submitting a PR I'm happy to merge.
