### ISSUE TITLE
Colons should not be escaped in TEXT property values

### ISSUE THREAD

**Issue by heyfrench** [adamgibbons/ics#67]
Great library. I noticed the `\` was showing up in my descriptions in Calendar.app, so I did a little digging and found this in the RFC. I'll try to get a PR in this week, but I wanted to document it just in case I can't.

From the RFC:
> However, a COLON character in a "TEXT" property value SHALL NOT be escaped with a BACKSLASH character.

Offending line: last `.replace()` in https://github.com/adamgibbons/ics/blob/master/src/utils/set-description.js#L2

**Comment by adamgibbons** [comment]
Good catch. Will keep this open and add to the queue.
