### ISSUE TITLE
Explain attribute "startType" (utc dates)

### ISSUE THREAD

**Issue by truefalse10** [adamgibbons/ics#72]
It took me quite a while to realize that i have to set the attribute `startType` to `local` in order to keep my UTC dates without conversion. It would be nice if the README would mention this feature

**Comment by janolivermr** [comment]
This still doesn't work properly though, since it will then omit the UTC designation (`Z` at the end of the date/time string)

**Comment by raine** [comment]
As @janolivermr pointed out, `startType` has no effect on whether input date is considered to be in UTC tz or not. It's always considered to be local time.

**Comment by george-i** [comment]
Maybe it helps someone: I'm doing  a hack, I replace the text in the generated file as follows:

`
ics.createEvent({
    title: 'My event',
    description: '',
    start: [1970,1,1,0,0],
    duration: {minutes: 60},
    organizer: { name: 'John Doe', email: 'john.doe@example.com' },
    attendees: [
      { name: 'John Doe', email: 'john.doe@example.com' }
    ]
  }, (err, value) => {
    if(err){
      next(err);
    }else{
	  let evFilename = 'ev_' + new Date().getTime() + '.ics';
      let newLineSplit = value.split(/\r?\n/);
      let newVal = '';
      newLineSplit.forEach(function (line) {
        if(line.startsWith('DTSTART')){
          newVal += 'DTSTART:'+utcDate+'\n';
        }else{
          newVal += line+'\n';
        }
      });

      fs.writeFile(__dirname+'/../../temp_files/'+evFilename, newVal, function (err, writeStat) {
        if(err){
          next(err);
        }else{
          next(null, evFilename);
        }
      });
    }
  });
`

**Comment by heijmerikx** [comment]
What @truefalse10 suggested works for me after hours of figuring out why my dockerized node.js application would display date values in my frontend (using momentjs) on my local (dockerized) environment and on AWS exactly the same.

The database was also the same at AWS and locally. 
The docker container has the timezone set as well.
Storing database values as UTC on a datetimetz type db field on postgres.

Only the ics would contain a difference in time, which drove me quite mad.
Locally on the same timezone the ical had the proper date set, but not on the server with the same docker image.

Now, after setting the starttype option it's solved for me. Thanks for that. I'm happy, but not satisfied ;)

**Comment by jcaron23** [comment]
I submitted PR #113 which should give more control over dates, including the choice of both the input type (local or UTC) and the output (floating or UTC).

**Comment by adamgibbons** [comment]
Addressed by #115
