### ISSUE TITLE
Resetting the `ics` for new usage

### ISSUE THREAD

**Issue by lfilho** [adamgibbons/ics#73]
Hey @adamgibbons thanks for the nice library!

I have a data structure with many people and many events for each people. My use case is to generate a .ics file for each person containing the events under them. Looking at your documentation I don't see a way to do that. What I want:

1. Iterate through my data structure (each person) (first loop)
2. For each person, iterate through their events (second loop)
3. Create events (`ics.createEvent`) 
4. Exit second loop && write .ics file for that person
5. Repeat for next person

But as of today's API, after each file write on step 4, it would only be appending to the same global ` ics` variable, hence each file write would contain the events for all previous persons instead of only theirs.

Would it be possible to add another api to reset the `ics` var? Or make it possible to make `ics` an instance (`var ics = new ICS()`)?

Thanks!!

**Comment by jfix** [comment]
@lfilho from what I understand, `ics.createEvent` will return an event, either via a callback, or as the actual return value. This is quite clear from the examples. The `ics` object itself is not altered.

Funnily enough, I'm doing something similar:
```
places.list().forEach((place) => {
  let c = [] // array containing ics calendar events
  y.forEach((day) => {
    const m = moment(day)
    const e = place.rules(m)
    if (e.length > 0) {
      c.push({
        start: [m.year(), m.month(), m.date(), 20, 0],
        duration: { minutes: 120 },
        title: `Tomorrow: ${e.join(' ,')}`,
        description: `Don't forget to put the following trash outside : ${e.join(', ')}`
      })
    }
  })
  const { err, ical } = ics.createEvents(c)

  if (!err) fs.writeFileSync(`${s.year()}/${place.id}.ics`, ical)
  else console.log(`ICAL error: ${err}`)
})
```

`ics` is just an object that exposes methods such as `createEvents`, it doesn't keep any state for a given event.

**Comment by lfilho** [comment]
You are correct! I mis-looked the examples and I guess my brain was just expecting a stateful one haha. Thanks!
