### ISSUE TITLE
Understanding default uid generation

### ISSUE THREAD

**Issue by aaronhong** [adamgibbons/ics#84]
Thanks for making this module.

Kind of new to Node.js. I'm trying to understand why the uuid's generated with uuid/v1 is the same for ICS files *created around the same time.* I'm wondering if this has something to do with how `defaults` is loaded? 

For the life cycle of a node.js app, when is the `uid` in `defaults` actually generated? Seems the way `defaults` is using the uuid generator causes the uuid to be fixed for each time it is `imported` into `buildEvent`. An [example quote from here](https://github.com/kelektiv/node-uuid/issues/117#issuecomment-391419333):
```
> const before = { myProperty: uuid.v4() }
undefined
> before.myProperty
'bdf9794f-0897-48dd-8fed-da380dac6e74'

> const after = { myProperty: () => uuid.v4() }
undefined
> after.myProperty
[Function: myProperty]
> after.myProperty()
'40848bdb-7c04-40e2-8694-5513db705732'
> after.myProperty()
'd1edd511-6ce9-4a12-b196-4fafb6b3b16f'
> after.myProperty()
'1258559b-c082-436c-8ecb-f74679954ffd'
> // Etc ...
```

**Comment by adamgibbons** [comment]
Fixed by #97
