### ISSUE TITLE
Library converts UTC to server time

### ISSUE THREAD

**Issue by c-moss-talk** [adamgibbons/ics#94]
Please correct me if I'm wrong, but when you are doing this in `set-date-with-utc-time.js` 
```
const formattedDate = moment([
      year,
      month - 1,
      date,
      hours,
      minutes,
      seconds
    ]).utc().format('YYYYMMDDTHHmm00') + 'Z'
```

you are calling `moment([...])`which will interpret the inputs as local. i.e., hours is the time on my watch in new york, not utc.

shouldn't it be `moment.utc([...])...`  ?

**Comment by adamgibbons** [comment]
@c-moss-talk thanks for looking into this issue. It should be resolved by #98, which I'll release to NPM shortly.
